import Head from "next/head";
import Logo from '@/components/ui/logo';
import Image from 'next/image'
import { BsLinkedin, BsFacebook } from "react-icons/bs";
import CustomerTable from "@/components/customer/customerTable";
import { api } from "@/utils/api";
import Loader from "@/components/loading";
import { useRouter } from 'next/router';

export default function Customer() {

    const router = useRouter()
    const customerData = api.blockChainRouter.getCustomerData.useQuery(Number(router.query.id))

    return (
        <>
            <Head>
                <title>BinTraWine</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen">
                <div className="grid md:grid-areas-customer md:grid-cols-customer md:grid-rows-customer grid-areas-customer-mobile grid-cols-customer-mobile grid-rows-customer-mobile min-h-screen">
                    <div className="flex flex-col grid-in-sidebar">
                        <div className="bg-primary flex-1">
                            <div className="flex flex-col gap-4 w-full h-full p-5">
                                <div className="flex flex-row justify-center items-center">
                                    <Logo className='fill-white p-0' width={80} height={80} />
                                    <p className='text-4xl text-white font-primary font-normal'>BinTraWine</p>
                                </div>
                                <div className="flex flex-row justify-center items-center">
                                    <div className="bg-accent flex flex-col justify-center items-center rounded-2xl p-2">
                                        <div className="rounded-xl">
                                            <Image src="/images/wine_image.png" width={200} height={200} alt="Wine Image" />
                                        </div>
                                        <div className="py-5">
                                            <p className="text-white font-extralight text-sm font-primary">Hai scansionato</p>
                                            <p className="text-white font-semibold text-xl font-primary">Poggesco DOC</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="bg-primary_light flex flex-row gap-10 px-7 pt-5 pb-10 grid-in-footer">
                        <div className="flex flex-col w-1/4 gap-2">
                            <p className="text-white text-base font-primary font-semibold">BinTraWine</p>
                            <p className="text-white text-base font-primary">Blockchain, Tracking and Tracing solutions for Wine</p>
                        </div>
                        <div className="flex flex-col flex-1 gap-2">
                            <p className="text-white text-base font-primary font-semibold">Vuoi saperne di più</p>
                            <p className="text-white text-base font-primary">Visita il <span className="underline">sito internet</span> oppure seguici sui nostri social</p>
                            <div className="flex flex-row gap-6">
                                <BsLinkedin className="text-white text-4xl hover:cursor-pointer" />
                                <BsFacebook className="text-white text-4xl hover:cursor-pointer" />
                            </div>
                        </div>
                    </div>
                    <div className="flex-1 p-11 flex flex-col gap-7 items-center bg-surface_dark grid-in-main">
                        <p className="text-primary font-primary font-medium text-2xl">Scopri tutti i dati certificati</p>
                        {customerData.isLoading && <div className="flex justify-center items-center"><Loader /></div>}
                        {customerData.isError && <div><p>Errore nel caricamento, provare a ricaricare o cambiare bottiglia</p></div>}
                        {customerData.isFetched &&
                            customerData.data!.exist ?
                            <CustomerTable data={[
                                { title: "Certificazione uva dell'appezzamento", value: customerData.data?.data?.certificazioneUva ?? "Dato Mancante" },
                                { title: "Dati di raccolta dell'uva", value: customerData.data?.data?.dataRaccolta ?? "Dato Mancante" },
                                { title: "Forniture utilizzate in coltivazione", value: customerData.data?.data?.datiFornitura ?? "Dato Mancante" },
                                { title: "Destinazione d'uso dell'uva", value: customerData.data?.data?.destinazioneUva ?? "Dato Mancante" },
                                { title: "Prodotti utilizzati in fase di vinificazione", value: customerData.data?.data?.prodottiVinificazione ?? "Dato Mancante" },
                                { title: "Presenza solfiti", value: customerData.data?.data?.solfiti ?? "Dato Mancante" },
                                { title: "Lista allergeni", value: customerData.data?.data?.allergeni ?? "Dato Mancante" },
                                { title: "Località di provenienza delle uve", value: customerData.data?.data?.localitaUve ?? "Dato Mancante" },
                                { title: "Gradazione alcolica", value: customerData.data?.data?.gradazioneAlcolica ?? "Dato Mancante" },
                                { title: "Temperatura durante il trasporto", value: customerData.data?.data?.temperaturaTrasporto ?? "Dato Mancante" },
                                { title: "Validazione dell'ente", value: customerData.data?.data?.validazione ?? "Dato Mancante" },
                                { title: "Certificazione dell'ente", value: customerData.data?.data?.certificazione ?? "Dato Mancante" }
                            ]} />
                            :
                            <p>Il vino non è disponibile</p>
                        }
                    </div>
                </div>
            </main>
        </>
    )
}