import Head from "next/head";
import ActorDescription from "@/components/actorDescription";

export default function LandingPage() {

  return (
    <>
      <Head>
        <title>BinTraWine</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ActorDescription className="w-60" actorDescription={{ title: "Analisi qualità prodotto", data: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam quis aliquam faucibus, nisl quam ultricies odio, nec ultricies nisl nunc eu nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam quis aliquam faucibus, nisl quam ultricies odio, nec ultricies nisl nunc eu nunc. " }} />
      </main>
    </>
  );
}